"""add token_address to asset model

Revision ID: 16b15760117c
Revises: d0ca9d0a8873
Create Date: 2025-01-14 03:09:18.511839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b15760117c'
down_revision = 'd0ca9d0a8873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_address', sa.String(length=42), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('token_address')

    # ### end Alembic commands ###
