"""add reject_reason to assets table

Revision ID: 1cc75a9b49bb
Revises: ed553a7a0386
Create Date: 2025-01-13 06:04:07.357803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc75a9b49bb'
down_revision = 'ed553a7a0386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reject_reason', sa.Text(), nullable=True))
        batch_op.alter_column('asset_type',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('REAL_ESTATE', 'SEMI_REAL_ESTATE', name='assettype'),
               existing_nullable=False)
        batch_op.alter_column('token_supply',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='assetstatus'),
               existing_nullable=False)
        batch_op.drop_column('contract_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_address', sa.VARCHAR(length=42), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='assetstatus'),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('token_supply',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('asset_type',
               existing_type=sa.Enum('REAL_ESTATE', 'SEMI_REAL_ESTATE', name='assettype'),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('reject_reason')

    # ### end Alembic commands ###
