"""Add description and token_code fields to Asset model

Revision ID: d0ca9d0a8873
Revises: 1cc75a9b49bb
Create Date: 2025-01-14 01:18:17.977217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ca9d0a8873'
down_revision = '1cc75a9b49bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_code', sa.String(length=10), server_default='000000', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('token_code')

    # ### end Alembic commands ###
