"""add is_self_trade field to trades table

Revision ID: ed553a7a0386
Revises: fec988f5e053
Create Date: 2025-01-13 05:27:32.693758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed553a7a0386'
down_revision = 'fec988f5e053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_self_trade', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('is_self_trade')

    # ### end Alembic commands ###
