"""Add contract_address field

Revision ID: fec988f5e053
Revises: 5933b2321554
Create Date: 2025-01-13 04:53:58.543830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec988f5e053'
down_revision = '5933b2321554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_address', sa.String(length=42), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('contract_address')

    # ### end Alembic commands ###
